# Method production .bash_profile
#
# !! DO NOT EDIT THIS FILE !!
# Place user customizations in ~/.mybashrc
#

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
