# Matches functionality of .bash_profile generated by Git for Windows

export SOURCED_BASH_PROFILE=true

# User specific environment and startup programs

# TODO: Need to compare next line against default `.bash_profile` files from
#       different OS installs
#PATH=${PATH}:${HOME}/.local/bin:${HOME}/bin

# These paths utilise the `bin` repository
# TODO: Need to better determine OS-specific path based on environment
#       variable
if [[ ${OSTYPE} == darwin* ]]; then
    PATH=${PATH}:${HOME}/bin/production/osx/$(arch)
elif [[ ${OSTYPE} == linux* ]]; then
    PATH=${PATH}:${HOME}/bin/production/linux/$(arch)
elif [[ ${OS} == Windows* ]]; then
    PATH=${PATH}:${HOME}/bin/production/windows/$(arch)
fi
export PATH

profile_file="${HOME}/.profile"
if [ -f "${profile_file}" ]; then
    . "${profile_file}"
fi

bashrc_file="${HOME}/.bashrc"
if [ -f "${bashrc_file}" ] && [ -z "${SOURCED_BASHRC}" ]; then
    echo "Sourcing ${bashrc_file}"
    . "${bashrc_file}"
fi

